version: '3.7'

services:
  web:
    build: ./
    command: python ./shortener/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./shortener/shortener/.env.dev